included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - DerivedData

disabled_rules:
  - cyclomatic_complexity
  - file_length
  - for_where
  - function_body_length
  - function_parameter_count
  - line_length
  - syntactic_sugar
  - trailing_comma
  - type_body_length

identifier_name:
  excluded:
    - id
    - ui
    - Included
    - Excluded
    - Architecture
    - Assertions
    - CustomRules
    - Component
    - RequireSyntax
    - DisallowSyntax
    - Owns
    - MayDependOn
    - DoesNotDependOn
    - MayUse
    - DoesNotUse
    - Applies
    - Declare
    - ContainSyntax
    - ContainSyntaxNode
    - Does
    - DoesNot
    - Declares
    - Requires
    - RequiresScoped
    - Disallows
    - NoDirectStringMatching
    - ApplyAssertions
    - DependencyBoundaries
    - SingleOwner
    - AcyclicDeclaredDependencies
    - Paths
    - Modules

reporter: "xcode"
