import Foundation

public struct ArchitectureSnapshot: Equatable, Sendable {
    public let commands: [String]
    public let rules: ArchitectureRules

    public init(
        commands: [String] = ["init", "lint", "scan", "snapshot", "explain"],
        configuration: ArchitectureConfiguration
    ) throws {
        self.commands = commands
        self.rules = try ArchitectureRules(configuration: configuration)
    }

    public init(commands: [String] = ["init", "lint", "scan", "snapshot", "explain"], rules: ArchitectureRules) {
        self.commands = commands
        self.rules = rules
    }

    public func render() -> String {
        let enabledRules = BuiltInRules.families(from: rules.ruleConfiguration)
            .compactMap { family in
                family.first(where: \.isEnabled)
            }
        var lines: [String] = []
        lines.append("# Bumper Bowling Architecture Snapshot")
        lines.append("")
        lines.append("Generated by `bumper snapshot`. Do not edit this file by hand; update the generator or architecture metadata instead.")
        lines.append("")
        lines.append("Bumper Bowling asserts architecture over SwiftSyntax-observed source facts, configured in familiar Swift.")
        lines.append("")
        lines.append("## Commands")
        lines.append("")

        for command in commands {
            lines.append("- `bumper \(command)`")
        }

        lines.append("")
        lines.append("## Pipeline")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart LR")
        lines.append("    Config[\"ArchitectureRules\"] --> Scanner[\"RepositoryScanner\"]")
        lines.append("    Scanner --> Input[\"RepositoryInput\"]")
        lines.append("    Input --> Runner[\"BumperProjectRunner\"]")
        lines.append("    Runner --> Syntax[\"RepositorySyntax: parse once\"]")
        lines.append("    Syntax --> Facts[\"memoized typed facts\"]")
        lines.append("    Facts --> Rules[\"RuleSet: built-in + project rules\"]")
        lines.append("    Config --> Rules")
        lines.append("    Rules --> Report[\"RuleReport\"]")
        lines.append("```")
        lines.append("")
        lines.append("## Rule Snapshots")

        for rule in enabledRules {
            lines.append("")
            lines.append("### `\(rule.id.rawValue)`")
            lines.append("")
            lines.append(rule.description)
            lines.append("")
            lines.append(contentsOf: Self.ruleSnapshot(for: rule))
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private static func snapshotNodeID(for rawValue: String) -> String {
        rawValue
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map { word in
                word.prefix(1).uppercased() + word.dropFirst()
            }
            .joined()
    }

    private static func ruleSnapshot(for rule: ArchitectureRule) -> [String] {
        let ruleNode = snapshotNodeID(for: rule.id.rawValue)
        var lines: [String] = []
        lines.append("```mermaid")
        lines.append("flowchart LR")

        switch rule.id {
        case .forbiddenImport:
            lines.append("    Imports[\"ArchitectureGraph.sourceFiles.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Forbidden[\"RuleSetting.values\"] --> \(ruleNode)")
        case .componentBoundary:
            lines.append("    Imports[\"ArchitectureGraph.componentImportEdges\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Modules[\"componentByModule\"] --> \(ruleNode)")
            lines.append("    Dependencies[\"allowed + forbidden dependencies\"] --> \(ruleNode)")
        case .duplicateOwnership:
            lines.append("    Paths[\"ComponentRule.paths\"] --> Ownership[\"path ownership conflicts\"]")
            lines.append("    Ownership --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .declaredDependencyCycle:
            lines.append("    Dependencies[\"ComponentRule.allowedDependencies\"] --> Graph[\"dependency graph\"]")
            lines.append("    Graph --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .storedProperties:
            lines.append("    Properties[\"ArchitectureGraph.sourceFiles.storedProperties\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"StoredPropertyRuleConfiguration\"] --> \(ruleNode)")
        case .syntaxConstructs:
            lines.append("    Constructs[\"ArchitectureGraph.sourceFiles.imperativeConstructs\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"SyntaxConstructRuleConfiguration\"] --> \(ruleNode)")
        case .syntaxKinds:
            lines.append("    Kinds[\"ArchitectureGraph.sourceFiles.syntaxNodes.nodeKinds\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"SyntaxKindRuleConfiguration\"] --> \(ruleNode)")
        case .syntaxNodes:
            lines.append("    Facts[\"ArchitectureGraph.sourceFiles.syntaxNodes.nodes\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"SyntaxNodeRuleConfiguration\"] --> \(ruleNode)")
        case .publicDeclarations:
            lines.append("    Declarations[\"ArchitectureGraph.sourceFiles.publicDeclarations\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"PublicDeclarationRuleConfiguration\"] --> \(ruleNode)")
        case .enumStateMachine:
            lines.append("    Enums[\"ArchitectureGraph.sourceFiles.enums\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Paths[\"PathRuleConfiguration.paths\"] --> \(ruleNode)")
        default:
            lines.append("    Facts[\"Repository facts\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        }

        lines.append("    \(ruleNode) --> Findings[\"RuleViolation[]\"]")
        lines.append("    Findings --> Report[\"RuleReport\"]")
        lines.append("```")
        return lines
    }
}
