import Foundation

public struct ArchitectureSnapshot: Equatable, Sendable {
    public let commands: [String]
    public let rules: ArchitectureRules

    public init(
        commands: [String] = ["init", "lint", "scan", "snapshot", "explain"],
        configuration: ArchitectureConfiguration
    ) throws {
        self.commands = commands
        self.rules = try ArchitectureRules(configuration: configuration)
    }

    public init(commands: [String] = ["init", "lint", "scan", "snapshot", "explain"], rules: ArchitectureRules) {
        self.commands = commands
        self.rules = rules
    }

    public func render() -> String {
        let enabledRules = RuleRegistry(configuration: rules.ruleConfiguration).enabledRules
        var lines: [String] = []
        lines.append("# Bumper Bowling Architecture Snapshot")
        lines.append("")
        lines.append("Generated by `bumper snapshot`. Do not edit this file by hand; update the generator or architecture metadata instead.")
        lines.append("")
        lines.append("Bumper Bowling is a tiny Swift DSL for asserting architecture over SwiftSyntax-observed source facts.")
        lines.append("")
        lines.append("## Commands")
        lines.append("")

        for command in commands {
            lines.append("- `bumper \(command)`")
        }

        lines.append("")
        lines.append("## Pipeline")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart LR")
        lines.append("    Config[\"ArchitectureRules\"] --> Scanner[\"RepositoryScanner\"]")
        lines.append("    Scanner --> SwiftSyntax[\"SwiftFileParser + SwiftSyntax\"]")
        lines.append("    SwiftSyntax --> Facts[\"RepositoryFacts\"]")
        lines.append("    Facts --> Graph[\"ArchitectureGraph\"]")
        lines.append("    Config --> Graph")
        lines.append("    Graph --> Rules[\"RuleRegistry\"]")
        lines.append("    Config --> Rules")
        lines.append("    Rules --> Report[\"LintReport\"]")
        lines.append("```")
        lines.append("")
        lines.append("## Rule Snapshots")

        for rule in enabledRules {
            lines.append("")
            lines.append("### `\(rule.id.rawValue)`")
            lines.append("")
            lines.append(rule.description)
            lines.append("")
            lines.append(contentsOf: Self.ruleSnapshot(for: rule))
        }

        return lines.joined(separator: "\n") + "\n"
    }

    private static func snapshotNodeID(for rawValue: String) -> String {
        rawValue
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map { word in
                word.prefix(1).uppercased() + word.dropFirst()
            }
            .joined()
    }

    private static func ruleSnapshot(for rule: ArchitectureRule) -> [String] {
        let ruleNode = snapshotNodeID(for: rule.id.rawValue)
        var lines: [String] = []
        lines.append("```mermaid")
        lines.append("flowchart LR")

        switch rule.id {
        case .forbiddenImport:
            lines.append("    Imports[\"ArchitectureGraph.sourceFiles.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Forbidden[\"RuleSetting.values\"] --> \(ruleNode)")
        case .subsystemBoundary:
            lines.append("    Imports[\"ArchitectureGraph.subsystemImportEdges\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Modules[\"subsystemByModule\"] --> \(ruleNode)")
            lines.append("    Dependencies[\"allowed + forbidden dependencies\"] --> \(ruleNode)")
        case .duplicateOwnership:
            lines.append("    Paths[\"SubsystemRule.paths\"] --> Ownership[\"path ownership conflicts\"]")
            lines.append("    Ownership --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .declaredDependencyCycle:
            lines.append("    Dependencies[\"SubsystemRule.allowedDependencies\"] --> Graph[\"dependency graph\"]")
            lines.append("    Graph --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .storedProperties:
            lines.append("    Properties[\"ArchitectureGraph.sourceFiles.storedProperties\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"StoredPropertyRuleConfiguration\"] --> \(ruleNode)")
        case .syntaxConstructs:
            lines.append("    Constructs[\"ArchitectureGraph.sourceFiles.imperativeConstructs\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"SyntaxConstructRuleConfiguration\"] --> \(ruleNode)")
        case .syntaxKinds:
            lines.append("    Kinds[\"ArchitectureGraph.sourceFiles.syntaxFacts.nodeKinds\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Policy[\"SyntaxKindRuleConfiguration\"] --> \(ruleNode)")
        case .enumStateMachine:
            lines.append("    Enums[\"ArchitectureGraph.sourceFiles.enums\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Paths[\"PathRuleConfiguration.paths\"] --> \(ruleNode)")
        }

        lines.append("    \(ruleNode) --> Findings[\"ArchitectureViolation[]\"]")
        lines.append("    Findings --> Report[\"LintReport\"]")
        lines.append("```")
        return lines
    }
}
