import Foundation

public enum BumperCommands {
    public static func initialize(at root: URL) throws {
        try ConfigurationLoader.writeSample(to: root)
        print("Created sample \(ConfigurationLoader.fileName)")
        print("Note: bumper 0.0 still uses its built-in config for CLI commands.")
    }

    public static func scan(root: URL) async throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let model = try await RepositoryScanner(configuration: configuration).scan(root: root)

        var lines: [String] = []
        lines.append("# Architecture Scan")
        lines.append("")
        lines.append("Files: \(model.files.count)")
        let subsystems = Set(model.files.map(\.subsystem.rawValue)).sorted().joined(separator: ", ")
        lines.append("Subsystems: \(subsystems)")
        lines.append("")
        lines.append("## Dependencies")

        for edge in model.dependencyEdges.sorted(by: { "\($0.sourceSubsystem.rawValue).\($0.importedModule.rawValue)" < "\($1.sourceSubsystem.rawValue).\($1.importedModule.rawValue)" }) {
            lines.append("- \(edge.sourceSubsystem) imports \(edge.importedModule)")
        }

        return lines.joined(separator: "\n")
    }

    public static func diagram(root: URL) throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let rules = try ArchitectureRules(configuration: configuration)
        let enabledRules = RuleRegistry(configuration: rules.ruleConfiguration).enabledRules
        let commandNames = ["init", "lint", "scan", "diagram", "explain"]

        var lines: [String] = []
        lines.append("# Bumper Bowling System Diagram")
        lines.append("")
        lines.append("Generated by `bumper diagram`. Do not edit this file by hand; update the generator or architecture metadata instead.")
        lines.append("")
        lines.append("Bumper Bowling is a tiny, syntax-first architecture linter. The 0.0 system has a real adapter boundary, but Swift is the only language surface.")
        lines.append("")
        lines.append("## Command Flow")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart TD")
        lines.append("    CLI[\"bumper CLI\"]")
        lines.append("")

        for commandName in commandNames {
            let nodeID = diagramNodeID(for: commandName)
            lines.append("    CLI --> \(nodeID)[\"\(commandName)\"]")
        }

        lines.append("")
        lines.append("    Init --> SampleConfig[\"writes sample BumperBowling.swift\"]")
        lines.append("")
        lines.append("    Lint --> ConfigLoader[\"ConfigurationLoader\"]")
        lines.append("    Scan --> ConfigLoader")
        lines.append("    Diagram --> ConfigLoader")
        lines.append("    Explain --> ConfigLoader")
        lines.append("")
        lines.append("    ConfigLoader --> BuiltInConfig[\"Built-in 0.0 config\"]")
        lines.append("")
        lines.append("    BuiltInConfig --> Rules[\"ArchitectureRules\"]")
        lines.append("    BuiltInConfig --> Scanner[\"RepositoryScanner\"]")
        lines.append("")
        lines.append("    Scanner --> IncludeExclude[\"include / exclude filtering\"]")
        lines.append("    IncludeExclude --> AdapterRouter[\"RepositoryLanguageAdapter\"]")
        lines.append("")
        lines.append("    AdapterRouter --> SwiftAdapter[\"SwiftLanguageAdapter\"]")
        lines.append("    SwiftAdapter --> SwiftParser[\"SwiftParser + SwiftSyntax\"]")
        lines.append("    SwiftParser --> SourceFacts[\"SourceFileFacts\"]")
        lines.append("")
        lines.append("    SourceFacts --> RepoFacts[\"RepositoryFacts\"]")
        lines.append("    RepoFacts --> RuleRegistry[\"RuleRegistry\"]")
        lines.append("")
        lines.append("    Rules --> RuleRegistry")
        lines.append("")

        for rule in enabledRules {
            let nodeID = diagramNodeID(for: rule.id.rawValue)
            lines.append("    RuleRegistry --> \(nodeID)[\"\(rule.id.rawValue)\"]")
        }

        lines.append("")

        for rule in enabledRules {
            lines.append("    \(diagramNodeID(for: rule.id.rawValue)) --> Report[\"LintReport\"]")
        }

        lines.append("")
        lines.append("    Report --> Console[\"Console output\"]")
        lines.append("    Report --> Exit[\"Exit nonzero only on error\"]")
        lines.append("```")
        lines.append("")
        lines.append("## Conceptual Layers")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart LR")
        lines.append("    DSL[\"Swift DSL\\nBumperConfiguration\"]")
        lines.append("    Config[\"ArchitectureConfiguration\\ninput shape\"]")
        lines.append("    TypedRules[\"ArchitectureRules\\ntyped domain model\"]")
        lines.append("    Scanner[\"RepositoryScanner\"]")
        lines.append("    Adapter[\"SwiftLanguageAdapter\"]")
        lines.append("    Facts[\"SourceFileFacts\\nRepositoryFacts\"]")
        lines.append("    Engine[\"RuleRegistry + Rules\"]")
        lines.append("    Report[\"LintReport\"]")
        lines.append("")
        lines.append("    DSL --> Config")
        lines.append("    Config --> TypedRules")
        lines.append("    Config --> Scanner")
        lines.append("    Scanner --> Adapter")
        lines.append("    Adapter --> Facts")
        lines.append("    TypedRules --> Engine")
        lines.append("    Facts --> Engine")
        lines.append("    Engine --> Report")
        lines.append("```")
        lines.append("")
        lines.append("## 0.0 Boundaries")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart TD")
        lines.append("    SwiftOnly[\"SourceLanguage.swift only\"]")
        lines.append("    AdapterBoundary[\"Adapter boundary exists\"]")
        lines.append("    Future[\"Other languages later\"]")
        lines.append("")
        lines.append("    SwiftOnly --> AdapterBoundary")
        lines.append("    AdapterBoundary -. \"adaptable, not implemented\" .-> Future")
        lines.append("")
        lines.append("    ConfigFile[\"BumperBowling.swift\"]")
        lines.append("    CLIConfig[\"Built-in CLI config\"]")
        lines.append("")
        lines.append("    ConfigFile -. \"sample typed API only in 0.0\" .-> CLIConfig")
        lines.append("```")
        lines.append("")
        lines.append("## Enabled Rules")
        lines.append("")

        for rule in enabledRules {
            lines.append("- `\(rule.id.rawValue)`: \(rule.description)")
        }

        lines.append("")
        lines.append("## Rule Diagrams")

        for rule in enabledRules {
            lines.append("")
            lines.append("### `\(rule.id.rawValue)`")
            lines.append("")
            lines.append(contentsOf: ruleDiagram(for: rule))
        }

        lines.append("")
        lines.append("## Summary")
        lines.append("")
        lines.append("The CLI loads configuration, the scanner turns Swift files into facts through the Swift adapter, the rule registry evaluates typed rules against typed facts, and the report prints plain console output. The design keeps parsing isolated from lint rules while avoiding extra language surfaces until they are real.")

        return lines.joined(separator: "\n") + "\n"
    }

    public static func lint(root: URL) async throws -> LintReport {
        let configuration = try ConfigurationLoader.load(from: root)
        let rules = try ArchitectureRules(configuration: configuration)
        let model = try await RepositoryScanner(rules: rules).scan(root: root)
        return ArchitectureLinter(rules: rules).lint(model)
    }

    public static func explain(path: URL, root: URL) async throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let scanner = try RepositoryScanner(configuration: configuration)
        let file = try await scanner.scanFile(path, root: root)

        var lines: [String] = []
        lines.append("# \(file.path.rawValue)")
        lines.append("")
        lines.append("Subsystem: \(file.subsystem)")
        let imports = file.imports.map(\.rawValue).joined(separator: ", ")
        lines.append("Imports: \(imports.isEmpty ? "none" : imports)")
        lines.append("")
        lines.append("## Public API")

        if file.publicDeclarations.isEmpty {
            lines.append("None detected.")
        } else {
            for declaration in file.publicDeclarations {
                lines.append("- \(declaration.kind.rawValue) \(declaration.name.rawValue)")
            }
        }

        return lines.joined(separator: "\n")
    }

    private static func diagramNodeID(for rawValue: String) -> String {
        rawValue
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map { word in
                word.prefix(1).uppercased() + word.dropFirst()
            }
            .joined()
    }

    private static func ruleDiagram(for rule: ArchitectureRule) -> [String] {
        let ruleNode = diagramNodeID(for: rule.id.rawValue)
        var lines: [String] = []
        lines.append("```mermaid")
        lines.append("flowchart LR")

        switch rule.id {
        case .forbiddenImport:
            lines.append("    Imports[\"SourceFileFacts.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Forbidden[\"RuleSetting.values\"] --> \(ruleNode)")
        case .subsystemBoundary:
            lines.append("    Imports[\"SourceFileFacts.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Modules[\"subsystemByModule\"] --> \(ruleNode)")
            lines.append("    Dependencies[\"allowed + forbidden dependencies\"] --> \(ruleNode)")
        case .duplicateOwnership:
            lines.append("    Paths[\"SubsystemRule.paths\"] --> Ownership[\"path ownership conflicts\"]")
            lines.append("    Ownership --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .dependencyCycle:
            lines.append("    Dependencies[\"SubsystemRule.allowedDependencies\"] --> Graph[\"dependency graph\"]")
            lines.append("    Graph --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .domainModels:
            lines.append("    Properties[\"SourceFileFacts.storedProperties\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Taste[\"DomainModelRuleConfiguration\"] --> \(ruleNode)")
        case .enumStateMachine:
            lines.append("    Enums[\"SourceFileFacts.enums\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Paths[\"PathRuleConfiguration.paths\"] --> \(ruleNode)")
        }

        lines.append("    \(ruleNode) --> Findings[\"ArchitectureViolation[]\"]")
        lines.append("    Findings --> Report[\"LintReport\"]")
        lines.append("```")
        return lines
    }
}
