import Foundation

public enum BumperCommands {
    public static func initialize(at root: URL) throws {
        try ConfigurationLoader.writeSample(to: root)
        print("Created sample \(ConfigurationLoader.fileName)")
        print("Note: bumper 0.0 still uses its built-in config for CLI commands.")
    }

    public static func scan(root: URL) async throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let model = try await RepositoryScanner(configuration: configuration).scan(root: root)

        var lines: [String] = []
        lines.append("# Architecture Scan")
        lines.append("")
        lines.append("Files: \(model.files.count)")
        let subsystems = Set(model.files.map(\.subsystem.rawValue)).sorted().joined(separator: ", ")
        lines.append("Subsystems: \(subsystems)")
        lines.append("")
        lines.append("## Dependencies")

        for edge in model.dependencyEdges.sorted(by: { "\($0.sourceSubsystem.rawValue).\($0.importedModule.rawValue)" < "\($1.sourceSubsystem.rawValue).\($1.importedModule.rawValue)" }) {
            lines.append("- \(edge.sourceSubsystem) imports \(edge.importedModule)")
        }

        return lines.joined(separator: "\n")
    }

    public static func snapshot(root: URL) throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let rules = try ArchitectureRules(configuration: configuration)
        let enabledRules = RuleRegistry(configuration: rules.ruleConfiguration).enabledRules
        let commandNames = ["init", "lint", "scan", "snapshot", "explain"]

        var lines: [String] = []
        lines.append("# Bumper Bowling Architecture Snapshot")
        lines.append("")
        lines.append("Generated by `bumper snapshot`. Do not edit this file by hand; update the generator or architecture metadata instead.")
        lines.append("")
        lines.append("Bumper Bowling is a tiny, syntax-first architecture linter.")
        lines.append("")
        lines.append("## Commands")
        lines.append("")

        for commandName in commandNames {
            lines.append("- `bumper \(commandName)`")
        }

        lines.append("")
        lines.append("## Pipeline")
        lines.append("")
        lines.append("```mermaid")
        lines.append("flowchart LR")
        lines.append("    Config[\"ArchitectureRules\"] --> Scanner[\"RepositoryScanner\"]")
        lines.append("    Scanner --> Swift[\"SwiftLanguageAdapter\"]")
        lines.append("    Swift --> Facts[\"RepositoryFacts\"]")
        lines.append("    Facts --> Rules[\"RuleRegistry\"]")
        lines.append("    Config --> Rules")
        lines.append("    Rules --> Report[\"LintReport\"]")
        lines.append("```")
        lines.append("")
        lines.append("## Rule Snapshots")

        for rule in enabledRules {
            lines.append("")
            lines.append("### `\(rule.id.rawValue)`")
            lines.append("")
            lines.append(rule.description)
            lines.append("")
            lines.append(contentsOf: ruleSnapshot(for: rule))
        }

        return lines.joined(separator: "\n") + "\n"
    }

    public static func lint(root: URL) async throws -> LintReport {
        let configuration = try ConfigurationLoader.load(from: root)
        let rules = try ArchitectureRules(configuration: configuration)
        let model = try await RepositoryScanner(rules: rules).scan(root: root)
        return ArchitectureLinter(rules: rules).lint(model)
    }

    public static func explain(path: URL, root: URL) async throws -> String {
        let configuration = try ConfigurationLoader.load(from: root)
        let scanner = try RepositoryScanner(configuration: configuration)
        let file = try await scanner.scanFile(path, root: root)

        var lines: [String] = []
        lines.append("# \(file.path.rawValue)")
        lines.append("")
        lines.append("Subsystem: \(file.subsystem)")
        let imports = file.imports.map(\.rawValue).joined(separator: ", ")
        lines.append("Imports: \(imports.isEmpty ? "none" : imports)")
        lines.append("")
        lines.append("## Public API")

        if file.publicDeclarations.isEmpty {
            lines.append("None detected.")
        } else {
            for declaration in file.publicDeclarations {
                lines.append("- \(declaration.kind.rawValue) \(declaration.name.rawValue)")
            }
        }

        return lines.joined(separator: "\n")
    }

    private static func snapshotNodeID(for rawValue: String) -> String {
        rawValue
            .split(whereSeparator: { !$0.isLetter && !$0.isNumber })
            .map { word in
                word.prefix(1).uppercased() + word.dropFirst()
            }
            .joined()
    }

    private static func ruleSnapshot(for rule: ArchitectureRule) -> [String] {
        let ruleNode = snapshotNodeID(for: rule.id.rawValue)
        var lines: [String] = []
        lines.append("```mermaid")
        lines.append("flowchart LR")

        switch rule.id {
        case .forbiddenImport:
            lines.append("    Imports[\"SourceFileFacts.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Forbidden[\"RuleSetting.values\"] --> \(ruleNode)")
        case .subsystemBoundary:
            lines.append("    Imports[\"SourceFileFacts.imports\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Modules[\"subsystemByModule\"] --> \(ruleNode)")
            lines.append("    Dependencies[\"allowed + forbidden dependencies\"] --> \(ruleNode)")
        case .duplicateOwnership:
            lines.append("    Paths[\"SubsystemRule.paths\"] --> Ownership[\"path ownership conflicts\"]")
            lines.append("    Ownership --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .dependencyCycle:
            lines.append("    Dependencies[\"SubsystemRule.allowedDependencies\"] --> Graph[\"dependency graph\"]")
            lines.append("    Graph --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
        case .domainModels:
            lines.append("    Properties[\"SourceFileFacts.storedProperties\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Taste[\"DomainModelRuleConfiguration\"] --> \(ruleNode)")
        case .enumStateMachine:
            lines.append("    Enums[\"SourceFileFacts.enums\"] --> \(ruleNode)[\"\(rule.id.rawValue)\"]")
            lines.append("    Paths[\"PathRuleConfiguration.paths\"] --> \(ruleNode)")
        }

        lines.append("    \(ruleNode) --> Findings[\"ArchitectureViolation[]\"]")
        lines.append("    Findings --> Report[\"LintReport\"]")
        lines.append("```")
        return lines
    }
}
